version: '3.5'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - web:/var/www
    ports:
      - 80:4200
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: $PWD/frontend
      o: bind